# Generated by Django 6.0.2 on 2026-02-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
