# Generated by Django 6.0.3 on 2026-03-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
