# Generated by Django 6.0.2 on 2026-03-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_img_path',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tournament_img_path',
        ),
        migrations.AddField(
            model_name='event',
            name='event_img',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='tournament_img',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/'),
        ),
    ]
