# Generated by Django 6.0.3 on 2026-03-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_class_point',
            field=models.BooleanField(blank=True, default=False, verbose_name='クラスポイント対象'),
        ),
    ]
