# Generated by Django 6.0.2 on 2026-02-27 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_img_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tournament-img/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='pdf_img_path',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tournament-pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
