# Generated by Django 6.0.2 on 2026-03-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_detail'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('event', 'status', 'order')},
        ),
    ]
